project:
  type: book

book:
  title: "Guides for Supervised Learning"
  author: "Edda Brandes"
  date: "spring 2022"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - visualization.qmd
    - model-accuracy.qmd
    - linear-regression.qmd
    - classification.qmd
    - beyond-linearity.qmd
    - tree-based.qmd
    - text-mining.qmd
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

