project:
  type: book

book:
  title: "Guides for Supervised Learning"
  author: "Edda Brandes"
  date: "spring 2022"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

