on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Install renv (working)
        shell: Rscript {0}
        run: install.packages("renv")

      - name: Init renv
        shell: Rscript {0}
        run: renv::init()

      - name: Debug
        run: head renv/activate.R

      - name: Force renv bootstrap
        run: rm -r renv/library

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}